# Generated by Django 4.1 on 2022-09-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.worker')),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='workgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.workgroup'),
        ),
    ]
